import Foundation

/// Decide si lo que se acaba de copiar entra en el historial o no.
///
/// Es la parte del módulo que más importa y la que no se ve: copiar una contraseña
/// del gestor y encontrártela después en un historial —en disco, si está activado
/// «Guardar en disco»— es lo que más se le reprocha a estos programas. Por eso la
/// decisión vive aquí, suelta y sin AppKit, y se prueba entera en `swift test`.
///
/// Son tres filtros, en orden de confianza:
/// 1. las marcas que la propia app pone en el portapapeles (lo más fiable),
/// 2. la lista de apps de las que nunca se guarda nada,
/// 3. la pausa manual.
enum ClipboardFilter {

    /// Marcas estándar de nspasteboard.org que ponen los gestores de contraseñas y
    /// quien copia cosas que no son para guardar.
    ///
    /// `Concealed` es «esto es un secreto» (1Password, KeePassXC y compañía la
    /// ponen); `Transient` es «esto dura un momento»; `AutoGenerated` es «esto lo ha
    /// escrito un programa, no una persona». Ninguna de las tres se guarda, esté la
    /// app en la lista o no: la app que copia sabe mejor que nosotros lo que acaba
    /// de poner ahí.
    static let privateTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    /// Gestores de contraseñas conocidos, para no obligar a nadie a añadirlos a mano.
    ///
    /// La marca `Concealed` de arriba ya cubre a los que se portan bien, pero no
    /// todos la ponen siempre (ni al copiar un usuario, una nota o una clave de
    /// recuperación), así que la lista es el cinturón además de los tirantes.
    ///
    /// Un identificador equivocado aquí no rompe nada —simplemente no coincide con
    /// ninguna app—, pero tampoco protege: por eso Ajustes enseña cuáles de estos
    /// están instalados de verdad en el Mac en vez de prometer la lista entera.
    static let passwordManagers: [String] = [
        "com.1password.1password",          // 1Password 8
        "com.agilebits.onepassword7",       // 1Password 7
        "com.agilebits.onepassword",        // 1Password 6 y el mini
        "com.bitwarden.desktop",            // Bitwarden
        "org.keepassxc.keepassxc",          // KeePassXC
        "com.apple.keychainaccess",         // Acceso a Llaveros
        "com.apple.Passwords",              // Contraseñas (macOS 15+)
        "in.sinew.Enpass-Desktop",          // Enpass
        "com.dashlane.Dashlane",            // Dashlane
        "com.lastpass.LastPass",            // LastPass
        "com.markmcguill.strongbox.mac",    // Strongbox
    ]

    /// ¿Se guarda esto en el historial?
    ///
    /// `types` son los tipos que hay en el portapapeles; `frontmostBundleID`, la app
    /// que estaba delante al copiar (`nil` si no se sabe: entonces no se puede culpar
    /// a nadie y se guarda). `excluded` es la lista ya montada por `exclusions(_:_:)`.
    static func shouldRecord(types: [String],
                             frontmostBundleID: String?,
                             excluded: Set<String>,
                             paused: Bool) -> Bool {
        if paused { return false }
        if types.contains(where: privateTypes.contains) { return false }
        return !excludes(frontmostBundleID, in: excluded)
    }

    /// La lista efectiva: lo que ha puesto el usuario y, si lo quiere, los gestores
    /// conocidos. Todo en minúsculas y sin espacios, que es como se compara.
    static func exclusions(userList: [String], includePasswordManagers: Bool) -> Set<String> {
        var list = Set(userList.map(normalize).filter { !$0.isEmpty })
        if includePasswordManagers { list.formUnion(passwordManagers.map(normalize)) }
        return list
    }

    /// ¿Está esta app en la lista?
    ///
    /// Vale el identificador exacto y también los que cuelgan de él: excluir
    /// `com.1password.1password` cubre a `com.1password.1password.helper`, que es
    /// quien copia en algunas versiones. Lo que no vale es parecerse por delante:
    /// `com.agilebits.onepassword7` no queda cubierto por `com.agilebits.onepassword`
    /// —son apps distintas— y por eso se compara el punto, no el prefijo a secas.
    static func excludes(_ bundleID: String?, in list: Set<String>) -> Bool {
        guard let bundleID else { return false }
        let id = normalize(bundleID)
        guard !id.isEmpty else { return false }
        if list.contains(id) { return true }
        return list.contains { id.hasPrefix($0 + ".") }
    }

    /// macOS trata los identificadores sin distinguir mayúsculas (`com.apple.Passwords`
    /// y `com.apple.passwords` son la misma app), así que se guardan y comparan igual.
    static func normalize(_ bundleID: String) -> String {
        bundleID.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
    }
}
