import XCTest
@testable import OmniMac

/// Qué entra en el historial del portapapeles y qué no. Como en el limpiador de
/// enlaces, importan más las pruebas de lo que **no** debe guardarse: una contraseña
/// colada en el historial es el fallo que no se puede permitir este módulo.
final class ClipboardFilterTests: XCTestCase {

    /// Un texto normal copiado de una app cualquiera, sin lista ni pausa.
    private func records(types: [String] = ["public.utf8-plain-text"],
                         from app: String? = "com.apple.TextEdit",
                         excluded: Set<String> = [],
                         paused: Bool = false) -> Bool {
        ClipboardFilter.shouldRecord(types: types, frontmostBundleID: app,
                                     excluded: excluded, paused: paused)
    }

    func testLoNormalSeGuarda() {
        XCTAssertTrue(records())
    }

    func testEnPausaNoSeGuardaNada() {
        XCTAssertFalse(records(paused: true))
    }

    // MARK: - Marcas del portapapeles

    func testMarcaDeConfidencial() {
        XCTAssertFalse(records(types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]))
    }

    func testMarcasTransitoriaYAutomatica() {
        XCTAssertFalse(records(types: ["org.nspasteboard.TransientType"]))
        XCTAssertFalse(records(types: ["org.nspasteboard.AutoGeneratedType"]))
    }

    /// La marca manda aunque la app no esté en ninguna lista: es la propia app la que
    /// avisa de que lo que acaba de copiar es un secreto.
    func testLaMarcaGanaSinListaNinguna() {
        XCTAssertFalse(records(types: ["org.nspasteboard.ConcealedType"],
                               from: "com.una.app.cualquiera", excluded: []))
    }

    // MARK: - Lista de apps

    func testAppEnLaLista() {
        XCTAssertFalse(records(from: "com.bitwarden.desktop", excluded: ["com.bitwarden.desktop"]))
    }

    func testAppFueraDeLaLista() {
        XCTAssertTrue(records(from: "com.apple.Safari", excluded: ["com.bitwarden.desktop"]))
    }

    /// Los identificadores no distinguen mayúsculas: da igual cómo se escriba.
    func testMayusculasDaIgual() {
        XCTAssertFalse(records(from: "com.Apple.Passwords",
                               excluded: ClipboardFilter.exclusions(userList: ["COM.APPLE.PASSWORDS"],
                                                                    includePasswordManagers: false)))
    }

    /// Quien copia en 1Password a veces es un proceso auxiliar que cuelga del
    /// identificador principal.
    func testLosAuxiliaresCuelganDeLaApp() {
        XCTAssertFalse(records(from: "com.1password.1password.helper",
                               excluded: ["com.1password.1password"]))
    }

    /// Pero parecerse por delante no basta: son apps distintas y excluir una no
    /// puede llevarse por delante a la otra.
    func testParecerseNoBasta() {
        XCTAssertTrue(records(from: "com.agilebits.onepassword7",
                              excluded: ["com.agilebits.onepassword"]))
        XCTAssertTrue(records(from: "com.bitwarden.desktop-beta",
                              excluded: ["com.bitwarden.desktop"]))
    }

    /// Sin app delante (nadie activo, o macOS no lo dice) no se puede culpar a
    /// nadie: se guarda, que es lo que hacía la app antes de existir la lista.
    func testSinAppDelanteSeGuarda() {
        XCTAssertTrue(records(from: nil, excluded: ["com.bitwarden.desktop"]))
        XCTAssertTrue(records(from: "  ", excluded: ["com.bitwarden.desktop"]))
    }

    /// Una entrada vacía en la lista no puede convertirse en «excluye todo».
    func testEntradaVaciaNoExcluyeATodos() {
        let lista = ClipboardFilter.exclusions(userList: ["", "   "], includePasswordManagers: false)
        XCTAssertTrue(lista.isEmpty)
        XCTAssertTrue(records(from: "com.apple.Safari", excluded: lista))
    }

    // MARK: - La lista efectiva

    func testLosGestoresConocidosSeSuman() {
        let conGestores = ClipboardFilter.exclusions(userList: ["com.mi.app"], includePasswordManagers: true)
        XCTAssertTrue(conGestores.contains("com.mi.app"))
        XCTAssertTrue(conGestores.contains("com.1password.1password"))
        XCTAssertFalse(records(from: "com.1password.1password", excluded: conGestores))
    }

    func testSinLosGestoresConocidosSoloValeLoDelUsuario() {
        let soloUsuario = ClipboardFilter.exclusions(userList: ["com.mi.app"], includePasswordManagers: false)
        XCTAssertEqual(soloUsuario, ["com.mi.app"])
        XCTAssertTrue(records(from: "com.1password.1password", excluded: soloUsuario))
    }

    /// Los identificadores de serie se guardan ya normalizados, porque se comparan
    /// con los de las apps en minúsculas (`com.apple.Passwords` se escribe así).
    func testLosDeSerieVanNormalizados() {
        let lista = ClipboardFilter.exclusions(userList: [], includePasswordManagers: true)
        XCTAssertEqual(lista, Set(lista.map(ClipboardFilter.normalize)))
        XCTAssertFalse(records(from: "com.apple.Passwords", excluded: lista))
    }

    /// La pausa se mira antes que nada: ni lista ni marcas hacen falta.
    func testLaPausaManda() {
        XCTAssertFalse(records(from: "com.apple.TextEdit", excluded: [], paused: true))
    }
}

/// Quién manda sobre la fila elegida en el panel: al desplazarse la lista, SwiftUI
/// avisa de que el puntero «pasa» por filas que en realidad no ha tocado nadie.
final class PanelSelectionTests: XCTestCase {
    func testSinAnclaMandaElRaton() {
        XCTAssertTrue(PanelSelection.hoverWins(anchor: nil, mouse: NSPoint(x: 10, y: 10)))
    }

    /// El ratón quieto mientras la lista se mueve: no cuenta.
    func testElRatonQuietoNoRobaLaFila() {
        let sitio = NSPoint(x: 400, y: 300)
        XCTAssertFalse(PanelSelection.hoverWins(anchor: sitio, mouse: sitio))
    }

    func testAlMoverElRatonVuelveAMandar() {
        XCTAssertTrue(PanelSelection.hoverWins(anchor: NSPoint(x: 400, y: 300),
                                               mouse: NSPoint(x: 400, y: 318)))
    }
}

/// El ritmo del sondeo del portapapeles.
///
/// Con una sola mirada por segundo, copiar dos cosas seguidas perdía la primera: el
/// contador salta de 5 a 7 y lo que hubiera en la 5 ya no existe en ningún sitio.
final class ClipboardPollIntervalTests: XCTestCase {
    func testRecienCopiadoSeMiraDeprisa() {
        XCTAssertEqual(ClipboardFeature.pollInterval(sinceLastChange: 0), 0.25)
        XCTAssertEqual(ClipboardFeature.pollInterval(sinceLastChange: 3.9), 0.25)
    }

    /// Y en reposo, exactamente igual que antes: es lo que miden las cifras de consumo.
    func testEnReposoVuelveAUnaVezPorSegundo() {
        XCTAssertEqual(ClipboardFeature.pollInterval(sinceLastChange: 4.1), 1.0)
        XCTAssertEqual(ClipboardFeature.pollInterval(sinceLastChange: 600), 1.0)
    }
}
